Remove MS Legacy Edge support
IronCoreLabs/ironweb pull request #97
Opened 2021-06-01 18:31 UTC by clintfred

And update version of recrypt-wasm-binding

DO NOT MERGE UNTIL recrypt-wasm-binding has been publicly released and updated in package.json

2021-06-01 22:31 UTC, coltfred requested changes
It seems like a few tests that were using the `isNativeCryptoSupported` as false should be removed as well as the commented out code that @giarc3 pointed out.

2021-06-01 22:31 UTC, coltfred commented on src/frame/worker/crypto/aes/tests/index.test.ts
> -            spyOn(CryptoUtils, "isNativeCryptoSupported").and.returnValue(false);
Seems like this test should be defunct right?

2021-06-01 22:31 UTC, coltfred commented on src/frame/worker/crypto/aes/tests/index.test.ts
> -            spyOn(CryptoUtils, "isNativeCryptoSupported").and.returnValue(false);
Seems like this test should be defunct right?

2021-06-01 22:31 UTC, coltfred commented on src/frame/worker/crypto/aes/tests/index.test.ts
> -            spyOn(CryptoUtils, "isNativeCryptoSupported").and.returnValue(false);
Seems like this test should be defunct right?

2021-06-02 00:26 UTC, clintfred commented
@cjyar Is there an easy way to remove the build caches? I made a new version of the (temporary) recrypt-wasm-binding-0.6.0 zip file, and it not happy. If not I can upload a new one with a different name.

2021-06-02 16:43 UTC, clintfred commented
> @cjyar Is there an easy way to remove the build caches? I made a new version of the (temporary) recrypt-wasm-binding-0.6.0 zip file, and it not happy. If not I can upload a new one with a different name.

I uploaded a new artifact, so that should allow it to build now.

2021-06-02 17:12 UTC, cjyar commented
> @cjyar Is there an easy way to remove the build caches? I made a new version of the (temporary) recrypt-wasm-binding-0.6.0 zip file, and it not happy. If not I can upload a new one with a different name.

I don't know what build cache it would be using. I don't see any caching actions in the workflows. Are you talking about this error?

> error https://drive.google.com/uc?export=download&id=1gSv3s59BCo38wASfp3_-P2vhPiz0psLY: Integrity check failed for "@ironcorelabs/recrypt-wasm-binding" (computed integrity doesn't match our records, got "sha512-D0Nb4MJdhEJRFbu3j1cU8p5b4lissWiQ2qvzHM8SzuvDpu3V95FmZhjoKS0faamPqY9d58JzCY4A62DvBx1tCQ== sha1-9ciguH3Z6WevJP5gxpSwW0LwYDA=")

That looks like a yarn error that could be caused by a few different things. I don't think our GitHub runners have a local cache, so it's more likely a problem with `yarn.lock`. [This post](https://www.seancdavis.com/blog/fix-yarn-integrity-check-failed/) has some advice.

2021-06-02 19:10 UTC, skeet70 approved these changes
No notes, good ripping.

2021-06-02 22:40 UTC, merged